spring:
  application:
    name: practice-prometheus


  datasource:
    url: jdbc:h2:mem:metrics
    username: admin
    password: admin
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

management:
  endpoints:
    web:
      exposure:
        include: 'health, info, metrics, prometheus'



logging:
  level:
    sql: debug
